import { getLanguage } from '../../../lib/i18n.js'

const repoMessages = {
  zh: {
    repoMaintenanceQuestion:
      '是否启用实验性远程仓库维护？启用后将完整克隆前后端仓库',
    repoInitNowQuestion: '是否现在初始化 GitHub 远程仓库配置？',
    repoInitFailedHint:
      '远程仓库初始化未完成。项目已保留，可稍后运行 fba-cli repo init',
    cmdRepo: '实验性仓库维护',
    cmdRepoInit: '初始化 GitHub 远程仓库配置（实验性）',
    cmdRepoStatus: '检查本地仓库维护状态（实验性）',
    cmdRepoPush: '以向导方式选择并推送干净提交（实验性）',
    cmdRepoSync: '以向导方式同步 origin/upstream（实验性）',
    useNotFbaProject: '当前目录不是 FBA 项目（未找到 .fba.json）',
    backendDirNotFound: '后端目录未找到',
    frontendDirNotFound: '前端目录未找到',
    repoInitProjectHint: '请在 FBA 项目内运行，或使用 -p 指定项目目录，或先运行 "fba-cli use"',
    repoInitConfirmProject: '为以下项目初始化仓库配置:',
    repoInitGithubToken: 'GitHub Token',
    repoInitTokenRequired: 'GitHub Token 不能为空',
    repoInitTokenDetected: '已检测到 GitHub Token 来源',
    repoInitGithubOwner: 'GitHub owner',
    repoInitOwnerRequired: 'Owner 不能为空',
    repoInitOwnerInvalid: 'Owner 只能包含字母、数字和连字符，且不能以连字符开头或结尾',
    repoInitUseDefaultRemotes: '使用以下远程仓库 URL？',
    repoInitRoleMain: '主仓',
    repoInitRoleBackend: '后端仓',
    repoInitRoleFrontend: '前端仓',
    repoInitRemoteUrl: '远程仓库 URL',
    repoInitRemoteRequired: '远程仓库 URL 不能为空',
    repoInitOnlyGithubHttps: '仅支持 GitHub HTTPS URL',
    repoInitRepoExistsUse: '已存在，是否复用？',
    repoInitRepoMissingCreate: '不存在，是否创建？',
    repoInitVisibilityFor: '仓库可见性:',
    repoInitPublic: '公开',
    repoInitPrivate: '私有',
    repoInitCreateRepo: '创建',
    repoInitReuseRepo: '复用',
    repoInitRefusedRepoHint:
      '未复用或创建所需仓库，已取消。请手动创建后重新运行 fba-cli repo init',
    repoInitLocalChanges: '本地将执行:',
    repoInitLocalBackendRemotes: '设置后端 origin/upstream',
    repoInitLocalFrontendRemotes: '设置前端 origin/upstream',
    repoInitLocalFullHistory: '如前后端是浅克隆，则拉取完整历史',
    repoInitLocalGitmodules: '写入主仓 .gitmodules',
    repoInitLocalMainGit: '如主目录还不是 Git 仓库，则初始化 main 分支',
    repoInitLocalCommitPrompt: '完成后询问是否创建本地初始化提交',
    repoInitNoPush: '不会执行 git push。',
    repoInitMissingChildrenQuestion: '检测到缺失或未初始化的子仓：{paths}。是否现在初始化这些子仓？',
    repoInitMissingChildrenFailed: '子仓初始化失败，请检查 .gitmodules、目录状态和网络后重新运行 fba-cli repo init。',
    repoInitMissingChildrenMainGitRequired:
      '主仓必须是 Git 仓库根目录，才能从 .gitmodules 初始化缺失子仓。请先克隆主仓或手动整理项目目录。',
    repoInitMissingChildrenGitlinkMissing:
      '主仓 HEAD 没有记录这些子仓的 gitlink：{paths}。请先从包含子模块指针的主仓提交运行 repo init，或先手动添加子模块。',
    repoInitNonEmptyChildDirUnsupported:
      '子仓目录 {paths} 已存在且不是 Git 根目录。repo init 不会覆盖其中的文件，请先手动备份、移走或整理为 Git 仓库。',
    repoInitMissingChildrenNewRepoUnsupported: '缺失子仓 {paths} 不能从本轮新建的空 GitHub 仓库初始化。请先提供已有子仓远程，或在本地创建子仓后再运行 repo init。',
    repoInitGitMissing: '未找到 git，请安装 Git 后重新运行 "fba-cli repo init"',
    repoInitChildGitRootRequired: '必须是 Git 仓库根目录',
    repoInitChildGitRootHint: '请确认前后端目录来自 fba-cli create 的克隆仓库，再重新运行 fba-cli repo init。',
    repoInitGithubAuthFailed:
      'GitHub Token 无效或已过期，请检查后重新运行 fba-cli repo init',
    repoInitGithubPermissionFailed:
      'GitHub 请求被拒绝，请检查 Token 权限、组织仓库权限或 GitHub 速率限制',
    repoInitGithubCreateFailed:
      'GitHub 仓库创建失败。仓库可能已存在，或名称/权限不符合要求',
    repoInitGithubRequestFailed: 'GitHub 请求失败',
    repoInitApplyFailed: '远程仓库初始化未完成。项目已保留，本地更改已回滚。',
    repoInitRollbackFailed: '本地更改回滚不完整，请检查 .gitmodules、.git 和子仓目录。',
    repoInitRetryHint: '请修复问题后重新运行: fba-cli repo init。已创建的远程仓库会保留。',
    repoInitCommitQuestion: '是否创建本地初始化提交？不会执行 git push。',
    repoInitMainDetachedCommitSkipped:
      '主仓当前处于 detached HEAD，已跳过本地初始化提交。请先切换到分支后手动提交。',
    repoInitStagingCommit: '暂存仓库元数据',
    repoInitCreatingCommit: '创建本地仓库初始化提交',
    repoInitCommitFailedHint:
      '本地初始化提交未创建。仓库配置已完成，请检查 git status 后手动提交。',
    repoInitNextSteps: '下一步',
    repoInitComplete: '仓库初始化完成',
    repoInitCancelled: '已取消仓库初始化',
    repoStatusTitle: '仓库维护状态',
    repoStatusConfirmProject: '检查以下项目的仓库状态:',
    repoStatusOverall: '整体状态',
    repoStatusHintOk: '仓库配置看起来正常。',
    repoStatusHintWarn: '存在可修正项，可运行 "fba-cli repo init" 重新整理本地仓库配置。',
    repoStatusHintManual: '存在需要手动判断的提示项，请根据上方状态检查本地仓库。',
    repoStatusHintError: '存在阻断问题，请根据上方状态手动检查并修正项目结构。',
    repoStatusDirMissing: '{label} 目录不存在',
    repoStatusGitOk: '{label} 是 Git 仓库',
    repoStatusGitError: '{label} 不是 Git 仓库',
    repoStatusRootOk: '{label} 是 Git 根目录',
    repoStatusRootWarn: '{label} 位于另一个 Git 仓库内部',
    repoStatusShallowOk: '{label} 已包含完整 Git 历史',
    repoStatusShallowWarn: '{label} 是浅克隆',
    repoStatusOriginOk: '{label} 已配置 origin',
    repoStatusOriginWarn: '{label} 未配置 origin',
    repoStatusBranchOk: '{label} 当前分支为 {branch}',
    repoStatusBranchWarn: '{label} 当前处于 detached HEAD 或没有当前分支',
    repoStatusUpstreamOk: '{label} upstream 指向官方仓库',
    repoStatusUpstreamWarn: '{label} upstream 未指向官方仓库',
    repoStatusUpstreamExists: '{label} 已配置 upstream',
    repoStatusWorkingTreeOk: '{label} 工作区干净',
    repoStatusWorkingTreeWarn: '{label} 工作区有本地改动',
    repoStatusWorkingTreeUnreadable: '{label} 工作区状态读取失败',
    repoStatusChildDirContentError:
      '{label} 目录已存在且不是 Git 根目录，repo init 不会覆盖其中的文件',
    repoStatusChangedItems: '{count} 个变更项',
    repoStatusGitmodulesMissing: '缺少 .gitmodules',
    repoStatusGitmodulesEntryMissing: '.gitmodules 缺少 {role} 条目',
    repoStatusGitmodulesPathOk: '.gitmodules 的 {role} path 正确',
    repoStatusGitmodulesPathWarn: '.gitmodules 的 {role} path 不匹配',
    repoStatusGitmodulesUrlOk: '.gitmodules 的 {role} url 与 origin 一致',
    repoStatusGitmodulesUrlWarn: '.gitmodules 的 {role} url 与 origin 不一致',
    repoStatusExpectedActual: '预期 {expected}，当前 {actual}',
    repoStatusMissing: '缺失',
    repoStatusOriginMissing: 'origin 缺失',
    repoStatusNextActionQuestion: '接下来要做什么？',
    repoStatusActionInit: '整理本地仓库配置',
    repoStatusActionInitHint: '运行 fba-cli repo init',
    repoStatusActionSync: '同步本地仓库',
    repoStatusActionSyncHint: '运行 fba-cli repo sync',
    repoStatusActionPush: '推送干净提交',
    repoStatusActionPushHint: '运行 fba-cli repo push',
    repoStatusActionExit: '暂时不处理',
    repoStatusNextSteps: '可执行命令',
    repoStatusComplete: '仓库状态检查完成',
    repoStatusCancelled: '已取消仓库状态检查',
    repoPushPlanTitle: '将按以下顺序推送:',
    repoPushConfirmProject: '为以下项目推送仓库:',
    repoPushNoHiddenActions: '不会执行 pull、merge、rebase、业务提交、tag push 或 force push。',
    repoPushChooseTargets: '本次要推送哪些仓库？',
    repoPushNoTargets: '未选择任何仓库，已取消推送。',
    repoPushPointerCommitQuestion: '检测到主仓子仓指针变化，是否创建本地主仓提交？',
    repoPushPointerSkipped: '已跳过主仓子仓指针提交。主仓不会记录当前子仓 HEAD。',
    repoPushPointerUnrelatedChanges: '主仓还有其它未提交改动，请先手动整理后再运行 fba-cli repo push。',
    repoPushPointerCommitFailed: '主仓子仓指针提交失败，请检查 git status 后手动处理。',
    repoPushPointerRequiresChildPush:
      '不能创建指向未选子仓提交的主仓指针提交。请同时选择对应子仓，或跳过本次指针提交后只推送主仓已有提交。',
    repoPushUnpushedSubmoduleRefs:
      '主仓当前提交引用了尚未推送到 origin、未包含在本次所选子仓 HEAD 中，或无法确认的子仓提交',
    repoPushMainRequiresPushedSubmodules:
      '不能安全推送主仓。请先整理并推送这些子仓，或让本次所选子仓 HEAD 包含主仓引用的提交。',
    repoPushWarnings: '警告:',
    repoPushPrecheckFailed: '仓库推送前检查未通过',
    repoPushFixHint: '请先在本地修正问题，再重新运行 fba-cli repo push。',
    repoPushCancelled: '已取消仓库推送',
    repoPushDryRunFailed: '推送预检查失败，未执行真实 push',
    repoPushFailed: '仓库推送失败',
    repoPushAlreadyPushed: '已推送',
    repoPushPending: '未推送',
    repoPushRetryHint: '部分仓库可能已经推送。请检查远程状态后重新运行 fba-cli repo push。',
    repoPushComplete: '仓库推送完成',
    repoPushStatusHint: '推送完成，可运行 fba-cli repo status 检查本地状态。',
    repoSyncPlanTitle: '将按以下顺序同步:',
    repoSyncNoHiddenActions: '不会执行 push、stash 或 force 操作；merge/rebase 只会在确认后执行。',
    repoSyncWarnings: '警告:',
    repoSyncConfirmProject: '为以下项目同步仓库:',
    repoSyncOriginPhase: '同步 origin',
    repoSyncUpstreamPhase: '同步 upstream',
    repoSyncState: '当前状态',
    repoSyncStateUpToDate: '已是最新',
    repoSyncStateFastForward: '远程有新提交，可快进',
    repoSyncStateAhead: '本地有提交，远程没有新提交',
    repoSyncStateDiverged: '本地和远程都有各自的新提交',
    repoSyncStateMissingRemoteBranch: '远程分支不存在',
    repoSyncStateUnknown: '无法判断',
    repoSyncRecommendedAction: '建议操作',
    repoSyncTarget: '目标',
    repoSyncChooseAction: '请选择处理方式',
    repoSyncChooseUpstreamBranch: '选择要跟随的 upstream 分支',
    repoSyncFollowUpstreamQuestion: '是否继续检查并跟随官方 upstream 更新？',
    repoSyncActionFastForwardOrigin: '快进到 origin',
    repoSyncActionRebaseOrigin: 'rebase 到 origin',
    repoSyncActionMergeOrigin: 'merge origin',
    repoSyncActionPushOrSkip: '保留本地提交，稍后 repo push',
    repoSyncActionFastForwardUpstream: '快进到 upstream',
    repoSyncActionRebaseUpstream: 'rebase 到 upstream',
    repoSyncActionMergeUpstream: 'merge upstream',
    repoSyncActionChooseUpstreamBranch: '选择 upstream 分支',
    repoSyncActionSkip: '跳过',
    repoSyncActionCancel: '取消同步',
    repoSyncActionFastForwardHint: '只移动指针，不产生新提交',
    repoSyncActionRebaseHint: '把本地提交重放到目标之后',
    repoSyncActionMergeHint: '保留历史，可能产生 merge commit',
    repoSyncActionPushOrSkipHint: '本地领先远程，建议之后运行 repo push',
    repoSyncRebasePublishedWarning: '检测到本地提交可能已经推送过，rebase 会改写历史；建议 merge。',
    repoSyncUpstreamMismatch: 'upstream 未指向官方仓库，跳过',
    repoSyncUpstreamFetchFailed: 'upstream fetch 失败',
    repoSyncUpstreamNoIncomingUpdates: '本地包含项目提交，官方 upstream 没有新提交，跳过',
    repoSyncMainMayRefreshProjectMetadata: '主仓可从 origin 更新；先更新主仓后，将用最新 .fba.json、.gitmodules 和子仓目录重新检查。',
    repoSyncConflictTitle: '发现冲突',
    repoSyncConflictQuestion: '如何处理这些冲突？',
    repoSyncConflictUseLocal: '保留本地改动',
    repoSyncConflictUseIncoming: '使用传入改动',
    repoSyncConflictManual: '手动解决',
    repoSyncConflictAbort: '中止本次操作',
    repoSyncConflictUseLocalHint: '自动选择当前本地内容',
    repoSyncConflictUseIncomingHint: '自动选择 origin/upstream 内容',
    repoSyncConflictManualHint: '停止后由你手动处理',
    repoSyncConflictAbortHint: '执行 git merge/rebase --abort',
    repoSyncConflictUnknownFiles: '未能读取冲突文件列表',
    repoSyncManualHint: '手动处理命令',
    repoSyncMainPointerChanges: '主仓检测到子仓指针变更',
    repoSyncMainPointerCommitQuestion: '是否在主仓创建一个本地提交记录这些指针变更？',
    repoSyncMainUnrelatedChanges: '主仓还有其它本地变更，请先手动处理',
    repoSyncBlocked: '仓库同步已阻断',
    repoSyncFixHint: '请先在本地修正问题，再重新运行 fba-cli repo sync。',
    repoSyncCancelled: '已取消仓库同步',
    repoSyncFailed: '仓库同步失败',
    repoSyncUpdated: '已更新',
    repoSyncSkipped: '已是最新，跳过',
    repoSyncPending: '未同步',
    repoSyncRetryHint: '部分仓库可能已经同步。请运行 fba-cli repo status 并检查 Git 状态。',
    repoSyncComplete: '仓库同步完成',
    repoSyncStatusHint: '同步完成，可运行 fba-cli repo status 检查本地状态。',
  },
  en: {
    repoMaintenanceQuestion:
      'Enable experimental repository maintenance? This will fully clone backend and frontend repositories',
    repoInitNowQuestion: 'Initialize GitHub remote repository setup now?',
    repoInitFailedHint:
      'Repository initialization did not complete. The project was kept. Run fba-cli repo init later',
    cmdRepo: 'Experimental repository maintenance',
    cmdRepoInit: 'Initialize GitHub remote repository setup (experimental)',
    cmdRepoStatus: 'Check local repository maintenance status (experimental)',
    cmdRepoPush: 'Choose and push clean commits with a guided workflow (experimental)',
    cmdRepoSync: 'Synchronize origin/upstream with a guided workflow (experimental)',
    useNotFbaProject: 'Current directory is not an FBA project (.fba.json not found)',
    backendDirNotFound: 'Backend directory not found',
    frontendDirNotFound: 'Frontend directory not found',
    repoInitProjectHint: 'Run this command inside an FBA project, use -p, or run "fba-cli use".',
    repoInitConfirmProject: 'Initialize repositories for',
    repoInitGithubToken: 'GitHub token',
    repoInitTokenRequired: 'GitHub token is required',
    repoInitTokenDetected: 'Detected GitHub token source',
    repoInitGithubOwner: 'GitHub owner',
    repoInitOwnerRequired: 'Owner is required',
    repoInitOwnerInvalid:
      'Owner may only contain letters, numbers, and hyphens, and cannot start or end with a hyphen',
    repoInitUseDefaultRemotes: 'Use these remote URLs?',
    repoInitRoleMain: 'Main',
    repoInitRoleBackend: 'Backend',
    repoInitRoleFrontend: 'Frontend',
    repoInitRemoteUrl: 'remote URL',
    repoInitRemoteRequired: 'Remote URL is required',
    repoInitOnlyGithubHttps: 'Only GitHub HTTPS URLs are supported',
    repoInitRepoExistsUse: 'exists. Use it?',
    repoInitRepoMissingCreate: 'does not exist. Create it?',
    repoInitVisibilityFor: 'Visibility for',
    repoInitPublic: 'Public',
    repoInitPrivate: 'Private',
    repoInitCreateRepo: 'Create',
    repoInitReuseRepo: 'Reuse',
    repoInitRefusedRepoHint:
      'Required repositories were not reused or created. Create them manually and rerun fba-cli repo init.',
    repoInitLocalChanges: 'Local changes:',
    repoInitLocalBackendRemotes: 'set backend origin/upstream',
    repoInitLocalFrontendRemotes: 'set frontend origin/upstream',
    repoInitLocalFullHistory: 'fetch full history if backend/frontend are shallow clones',
    repoInitLocalGitmodules: 'write main .gitmodules',
    repoInitLocalMainGit: 'initialize the main branch if the project directory is not a Git repo root',
    repoInitLocalCommitPrompt: 'ask whether to create a local initialization commit afterward',
    repoInitNoPush: 'No git push will be executed.',
    repoInitMissingChildrenQuestion: 'Missing or uninitialized child repositories detected: {paths}. Initialize them now?',
    repoInitMissingChildrenFailed: 'Child repository initialization failed. Check .gitmodules, directory state, and network, then rerun fba-cli repo init.',
    repoInitMissingChildrenMainGitRequired:
      'The main repository must be a Git root before missing child repositories can be initialized from .gitmodules. Clone the main repository or fix the project directory first.',
    repoInitMissingChildrenGitlinkMissing:
      'The main HEAD does not record gitlinks for these child repositories: {paths}. Run repo init from a main commit with submodule pointers, or add the submodules manually first.',
    repoInitNonEmptyChildDirUnsupported:
      'Child directories {paths} already exist and are not Git roots. repo init will not overwrite their files; back them up, move them away, or make them Git repositories first.',
    repoInitMissingChildrenNewRepoUnsupported: 'Missing child repositories {paths} cannot be initialized from newly-created empty GitHub repositories. Provide existing child remotes, or create the child repositories locally before rerunning repo init.',
    repoInitGitMissing: 'git was not found. Install Git and rerun "fba-cli repo init".',
    repoInitChildGitRootRequired: 'must be a Git repository root',
    repoInitChildGitRootHint:
      'Make sure backend and frontend directories are cloned repositories from fba-cli create, then rerun fba-cli repo init.',
    repoInitGithubAuthFailed:
      'GitHub token is invalid or expired. Check it and rerun fba-cli repo init.',
    repoInitGithubPermissionFailed:
      'GitHub request was denied. Check token scopes, organization permissions, or GitHub rate limits.',
    repoInitGithubCreateFailed:
      'GitHub repository creation failed. The repository may already exist, or the name/permissions may be invalid.',
    repoInitGithubRequestFailed: 'GitHub request failed',
    repoInitApplyFailed:
      'Repository initialization did not complete. The project was kept and local changes were rolled back.',
    repoInitRollbackFailed:
      'Local rollback did not complete. Check .gitmodules, .git, and child repository directories.',
    repoInitRetryHint:
      'Fix the issue and run: fba-cli repo init. Created remote repositories are kept.',
    repoInitCommitQuestion: 'Create a local initialization commit? No push will be executed.',
    repoInitMainDetachedCommitSkipped:
      'Main repository is detached. The local initialization commit was skipped; switch to a branch and commit manually.',
    repoInitStagingCommit: 'Staging repository metadata',
    repoInitCreatingCommit: 'Creating local repository init commit',
    repoInitCommitFailedHint:
      'The local initialization commit was not created. Repository setup is complete; check git status and commit manually.',
    repoInitNextSteps: 'Next steps',
    repoInitComplete: 'Repository initialization complete',
    repoInitCancelled: 'Repository initialization cancelled',
    repoStatusTitle: 'Repository maintenance status',
    repoStatusConfirmProject: 'Check repository status for',
    repoStatusOverall: 'Overall status',
    repoStatusHintOk: 'Repository configuration looks good.',
    repoStatusHintWarn:
      'Some items can be fixed. Run "fba-cli repo init" to refresh local repository setup.',
    repoStatusHintManual:
      'Some warnings need manual judgment. Inspect the repository state above.',
    repoStatusHintError:
      'Blocking issues found. Inspect the status above and fix the project structure manually.',
    repoStatusDirMissing: '{label} directory is missing',
    repoStatusGitOk: '{label} is a git repository',
    repoStatusGitError: '{label} is not a git repository',
    repoStatusRootOk: '{label} is a git root',
    repoStatusRootWarn: '{label} is inside another git repository',
    repoStatusShallowOk: '{label} has full git history',
    repoStatusShallowWarn: '{label} is a shallow clone',
    repoStatusOriginOk: '{label} has origin remote',
    repoStatusOriginWarn: '{label} has no origin remote',
    repoStatusBranchOk: '{label} current branch is {branch}',
    repoStatusBranchWarn: '{label} is detached or has no current branch',
    repoStatusUpstreamOk: '{label} upstream matches official repository',
    repoStatusUpstreamWarn: '{label} upstream does not match official repository',
    repoStatusUpstreamExists: '{label} has upstream remote',
    repoStatusWorkingTreeOk: '{label} working tree is clean',
    repoStatusWorkingTreeWarn: '{label} working tree has local changes',
    repoStatusWorkingTreeUnreadable: '{label} working tree status could not be read',
    repoStatusChildDirContentError:
      '{label} exists but is not a Git root; repo init will not overwrite files in it',
    repoStatusChangedItems: '{count} changed item(s)',
    repoStatusGitmodulesMissing: '.gitmodules is missing',
    repoStatusGitmodulesEntryMissing: '.gitmodules has no {role} entry',
    repoStatusGitmodulesPathOk: '.gitmodules {role} path matches',
    repoStatusGitmodulesPathWarn: '.gitmodules {role} path does not match',
    repoStatusGitmodulesUrlOk: '.gitmodules {role} url matches origin',
    repoStatusGitmodulesUrlWarn: '.gitmodules {role} url does not match origin',
    repoStatusExpectedActual: 'expected {expected}, actual {actual}',
    repoStatusMissing: 'missing',
    repoStatusOriginMissing: 'origin missing',
    repoStatusNextActionQuestion: 'What would you like to do next?',
    repoStatusActionInit: 'Refresh local repository setup',
    repoStatusActionInitHint: 'run fba-cli repo init',
    repoStatusActionSync: 'Synchronize local repositories',
    repoStatusActionSyncHint: 'run fba-cli repo sync',
    repoStatusActionPush: 'Push clean commits',
    repoStatusActionPushHint: 'run fba-cli repo push',
    repoStatusActionExit: 'Not now',
    repoStatusNextSteps: 'Command to run',
    repoStatusComplete: 'Repository status check complete',
    repoStatusCancelled: 'Repository status check cancelled',
    repoPushPlanTitle: 'Repositories will be pushed in this order:',
    repoPushConfirmProject: 'Push repositories for',
    repoPushNoHiddenActions: 'No pull, merge, rebase, business commit, tag push, or force push will run.',
    repoPushChooseTargets: 'Which repositories should be pushed this time?',
    repoPushNoTargets: 'No repositories selected. Push cancelled.',
    repoPushPointerCommitQuestion: 'Main repository submodule pointer changes detected. Create a local main commit?',
    repoPushPointerSkipped: 'Main pointer commit skipped. Main will not record the current child HEADs.',
    repoPushPointerUnrelatedChanges: 'Main repository has other uncommitted changes. Handle them manually before rerunning fba-cli repo push.',
    repoPushPointerCommitFailed: 'Main pointer commit failed. Check git status and handle it manually.',
    repoPushPointerRequiresChildPush:
      'Cannot create a main pointer commit for child repositories that are not selected for this push. Select the affected child repositories, or skip the pointer commit and push existing main commits only.',
    repoPushUnpushedSubmoduleRefs:
      'Main currently references child commits that are not on origin, not contained in the selected child HEAD, or cannot be verified',
    repoPushMainRequiresPushedSubmodules:
      'Cannot safely push main. Push these child repositories first, or make the selected child HEAD contain the commit referenced by main.',
    repoPushWarnings: 'Warnings:',
    repoPushPrecheckFailed: 'Repository push precheck failed',
    repoPushFixHint: 'Fix the local issues and rerun fba-cli repo push.',
    repoPushCancelled: 'Repository push cancelled',
    repoPushDryRunFailed: 'Push dry-run failed. No real push was executed.',
    repoPushFailed: 'Repository push failed',
    repoPushAlreadyPushed: 'Already pushed',
    repoPushPending: 'Not pushed',
    repoPushRetryHint:
      'Some repositories may already be pushed. Check remote state before rerunning fba-cli repo push.',
    repoPushComplete: 'Repository push complete',
    repoPushStatusHint: 'Push complete. Run fba-cli repo status to check local state.',
    repoSyncPlanTitle: 'Repositories will be synced in this order:',
    repoSyncNoHiddenActions: 'No push, stash, or force operation will run; merge/rebase only run after confirmation.',
    repoSyncWarnings: 'Warnings:',
    repoSyncConfirmProject: 'Synchronize repositories for',
    repoSyncOriginPhase: 'Synchronize origin',
    repoSyncUpstreamPhase: 'Synchronize upstream',
    repoSyncState: 'State',
    repoSyncStateUpToDate: 'up to date',
    repoSyncStateFastForward: 'remote has incoming commits; fast-forward is available',
    repoSyncStateAhead: 'local commits exist; remote has no incoming commits',
    repoSyncStateDiverged: 'local and remote both have unique commits',
    repoSyncStateMissingRemoteBranch: 'remote branch is missing',
    repoSyncStateUnknown: 'unknown',
    repoSyncRecommendedAction: 'Recommended action',
    repoSyncTarget: 'target',
    repoSyncChooseAction: 'Choose how to handle this repository',
    repoSyncChooseUpstreamBranch: 'Choose upstream branch to follow',
    repoSyncFollowUpstreamQuestion: 'Continue checking and following official upstream updates?',
    repoSyncActionFastForwardOrigin: 'Fast-forward from origin',
    repoSyncActionRebaseOrigin: 'Rebase onto origin',
    repoSyncActionMergeOrigin: 'Merge origin',
    repoSyncActionPushOrSkip: 'Keep local commits and push later',
    repoSyncActionFastForwardUpstream: 'Fast-forward from upstream',
    repoSyncActionRebaseUpstream: 'Rebase onto upstream',
    repoSyncActionMergeUpstream: 'Merge upstream',
    repoSyncActionChooseUpstreamBranch: 'Choose upstream branch',
    repoSyncActionSkip: 'Skip',
    repoSyncActionCancel: 'Cancel sync',
    repoSyncActionFastForwardHint: 'moves the branch pointer only',
    repoSyncActionRebaseHint: 'replays local commits after the target',
    repoSyncActionMergeHint: 'preserves history and may create a merge commit',
    repoSyncActionPushOrSkipHint: 'local branch is ahead; run repo push later',
    repoSyncRebasePublishedWarning: 'Local commits may already be pushed; rebase rewrites history. Merge is recommended.',
    repoSyncUpstreamMismatch: 'upstream does not match the official repository; skipped',
    repoSyncUpstreamFetchFailed: 'upstream fetch failed',
    repoSyncUpstreamNoIncomingUpdates: 'Local project commits exist, but official upstream has no incoming commits; skipped',
    repoSyncMainMayRefreshProjectMetadata: 'Main can update from origin. After updating main, the project will be checked again with the latest .fba.json, .gitmodules, and child directories.',
    repoSyncConflictTitle: 'Conflict detected',
    repoSyncConflictQuestion: 'How should these conflicts be handled?',
    repoSyncConflictUseLocal: 'Keep local changes',
    repoSyncConflictUseIncoming: 'Use incoming changes',
    repoSyncConflictManual: 'Resolve manually',
    repoSyncConflictAbort: 'Abort this operation',
    repoSyncConflictUseLocalHint: 'automatically choose current local content',
    repoSyncConflictUseIncomingHint: 'automatically choose origin/upstream content',
    repoSyncConflictManualHint: 'stop so you can resolve manually',
    repoSyncConflictAbortHint: 'run git merge/rebase --abort',
    repoSyncConflictUnknownFiles: 'Could not read conflicted file list',
    repoSyncManualHint: 'Manual recovery commands',
    repoSyncMainPointerChanges: 'Main repository submodule pointer changes detected',
    repoSyncMainPointerCommitQuestion: 'Create a local main-repository commit for these pointer changes?',
    repoSyncMainUnrelatedChanges: 'Main repository has unrelated local changes. Please handle them manually first.',
    repoSyncBlocked: 'Repository sync blocked',
    repoSyncFixHint: 'Fix the local issues and rerun fba-cli repo sync.',
    repoSyncCancelled: 'Repository sync cancelled',
    repoSyncFailed: 'Repository sync failed',
    repoSyncUpdated: 'Updated',
    repoSyncSkipped: 'Already up to date',
    repoSyncPending: 'Not synced',
    repoSyncRetryHint: 'Some repositories may already be synced. Run fba-cli repo status and inspect Git state.',
    repoSyncComplete: 'Repository sync complete',
    repoSyncStatusHint: 'Sync complete. Run fba-cli repo status to check local state.',
  },
} as const

type RepoMessageKey = keyof (typeof repoMessages)['zh']

export function rt(key: RepoMessageKey, params?: Record<string, string>): string {
  let message: string = repoMessages[getLanguage()][key] ?? key
  if (params) {
    for (const [param, value] of Object.entries(params)) {
      message = message.replaceAll(`{${param}}`, value)
    }
  }
  return message
}
